version: '3.4'

services:
  customerwebapis:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

  productwebapis:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"


  orderwebapis:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"


  api_gateway:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

